package ReverseApp;


/**
* ReverseApp/_ReverseImplBase.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Tuesday, 9 March, 2021 11:02:58 AM IST
*/

public abstract class _ReverseImplBase extends org.omg.CORBA.portable.ObjectImpl
                implements ReverseApp.Reverse, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors
  public _ReverseImplBase ()
  {
  }

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("reverseString", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ReverseApp/Reverse/reverseString
       {
         String str = in.read_string ();
         String $result = null;
         $result = this.reverseString (str);
         $result = $result + $result;
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ReverseApp/Reverse:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }


} // class _ReverseImplBase
