package ReverseApp;


/**
* ReverseApp/ReverseOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Reverse.idl
* Tuesday, 8 June, 2021 1:04:19 PM IST
*/

public interface ReverseOperations 
{
  String reverseString (String str);
} // interface ReverseOperations
